services:
  backend:
    build: ./backend/api
    container_name: backend_api
    ports:
      - "8080:8080"
    env_file:
      - backend/api/.env.local
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/stemadeleine_dev
      SPRING_DATASOURCE_USERNAME: dev_user
      SPRING_DATASOURCE_PASSWORD: dev_pass
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db

  frontoffice:
    build: frontend/frontoffice
    container_name: frontoffice
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:8080
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backoffice:
    build: ./frontend/backoffice
    container_name: backoffice
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stemadeleine_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: